deployment:
  tasks:
    - export DEPLOYPATH=/home1/cpkenn38/fabiofonseca.com.br/tjjud
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R licenses $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R .cpanel.yml $DEPLOYPATH
    #- /bin/cp -R .env $DEPLOYPATH
    - /bin/cp -R vite.config.js $DEPLOYPATH
    - /bin/cp -R phpunit.xml $DEPLOYPATH
    - /bin/cp -R package.json $DEPLOYPATH
    - /bin/cp -R composer.lock $DEPLOYPATH
    - /bin/cp -R artisan $DEPLOYPATH
    - /bin/cp -R README.md $DEPLOYPATH
    - /bin/cp -R .gitignore $DEPLOYPATH
    - /bin/cp -R composer.json $DEPLOYPATH

    - name: Install Composer dependencies
      command: |
        /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist --optimize-autoloader


    - name: Set storage and bootstrap/cache permissions
      command: |
	chmod -R 775 storage
	chmod -R 775 bootstrap/cache
	mkdir -p storage/framework/cache
	mkdir -p storage/framework/sessions
	mkdir -p storage/framework/views

    - name: Run Laravel migrations
      command: |
        php artisan migrate --force

    - name: Clear caches
      command: |
        php artisan config:cache
	php artisan cache:clear
        php artisan route:cache
        php artisan view:cache


-----
chmod -R 775 storage
chmod -R 775 bootstrap/cache
mkdir -p storage/framework/cache
mkdir -p storage/framework/sessions
mkdir -p storage/framework/views
